### ISSUE TITLE
Possible to extend to other generic types?

### ISSUE THREAD

**Issue by angerman** [lymar/hastache#30]
I was trying to add a `Data.Decimal` (http://hackage.haskell.org/package/Decimal) to a record, but was unable to use that as a context, as the type was not supported.

Is there an easy way to add support for this from the calling code? If so, what would be needed?

**Comment by co-dan** [comment]
As it turns out from #45, accessing the custom value via the `.ConstructorName` is *not* a good compromise! Will have to think about something else (and break some code as a result)
