### ISSUE TITLE
make hastacheStr pure

### ISSUE THREAD

**Issue by nurpax** [lymar/hastache#33]
For some reason the `hastacheStr` entry point has a MonadIO constraint:

`hastacheStr :: MonadIO m => MuConfig m -> Text -> MuContext m -> m Text`

Is there a reason for this function not being pure?  It'd be usable in more contexts than currently if it didn't require MonadIO.

**Comment by MichaelXavier** [comment]
It would still be nice to have a pure variant that didn't support partials and used ST or something instead of ioRef.
