### ISSUE TITLE
hastache-0.6.1 incompatible with GHC 7.0

### ISSUE THREAD

**Issue by hvr** [lymar/hastache#43]
Please either fix `hastache` or add a `base >= 4.4` constraint to future `hastache` releases

```
$ cabal build
Building hastache-0.6.1...
Preprocessing library hastache-0.6.1...
[1 of 2] Compiling Text.Hastache    ( Text/Hastache.hs, dist/build/Text/Hastache.o )

Text/Hastache.hs:125:23:
    Illegal instance declaration for `Monoid (MuContext m)'
      (All instance types must be of the form (T t1 ... tn)
       where T is not a synonym.
       Use -XTypeSynonymInstances if you want to disable this.)
    In the instance declaration for `Monoid (MuContext m)'
```

(and it's not enough to enable `-XTypeSynonymInstances`)

**Comment by co-dan** [comment]
Thank you for reporting this, @hvr. I really need to work on setting up viable bounds for *all* of hastache dependencies. I've been too lazy to do that, but it's clear now that it has to be done sooner or later (preferably, sooner).

Do you know if there is a way to (automatically) test a library with different versions of dependencies?

**Comment by hvr** [comment]
> Do you know if there is a way to (automatically) test a library with different versions of dependencies?

I don't have a full solution for that yet; but here's some pointers of more or less incomplete approaches OTTOMH:

 - http://hackage.haskell.org/package/sunlight
 - https://ghc.haskell.org/~hvr/buildreports/hastache.html (created by https://github.com/hvr/hackage-matrix-builder)
 - https://github.com/hvr/multi-ghc-travis

**Comment by Shimuuar** [comment]
I just want to say that multi-ghc-tracis is immensely useful and I catched a lot of regressions with it.
